name: Build and Publish

on:
  - workflow_dispatch
  - workflow_call

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cibw_archs: auto64

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16
        env:
          CIBW_BUILD_FRONTEND: build
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.7"
          CIBW_SKIP: "pp* *musllinux*"
          CIBW_ARCHS: ${{ matrix.cibw_archs }}
          CIBW_TEST_COMMAND: cd {project}/ && python tests/basic.py
        with:
          package-dir: ./

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl

  test_source:
    uses: ./.github/workflows/unittest.yml

  build_sdist:
    needs: test_source
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist .

      - uses: actions/upload-artifact@v4
        with:
          path: ./dist/*.tar.gz