name: Test

on:
  - push
  - pull_request
  - workflow_call

jobs:
  test:
    name: Test on ${{ matrix.os }}, ${{ matrix.install_from }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        install_from: [source, source_with_pre, sdist]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install from source
        if: matrix.install_from == 'source'
        run: pip install .

      - name: Install from source with prerelease.
        if: matrix.install_from == 'source_with_pre'
        # This tests compatibility with pre-release dependencies
        run: pip install --pre .

      - name: Install from sdist
        if: matrix.install_from == 'sdist'
        shell: bash
        run: |
          pipx run build --sdist .
          pip install ./dist/*.tar.gz

      - name: Run test cases
        run: python tests/basic.py